import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/nav";
import RootWrapper from "@/components/view/RootWrapper";
import { Footer } from "@/components/shared/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-[1100px]  overflow-x-auto mx-auto`}>
      <Navbar/> 
      <RootWrapper>
        {children}
        </RootWrapper>
        <Footer/>
        </body>
    </html>
  );
}
